# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: CC-BY-NC-4.0
"""
Prompts for patient profile generation.

Contains the ENRICHMENT_PROMPT used by the patient generator to create
realistic patient profiles, stories, and scenario complexity classifications.
"""

# Fields generated by benchmark seed generator vs sandbox:
#
# BENCHMARK SEED GENERATOR generates:
#   - account_info (age_in_years, timezone)
#   - personal_info (first_name, last_name, preferred_name, dob, sex, gender, pronouns)
#   - addresses (address1, address2, city, state, zip, is_preferred)
#   - phone_numbers (number, kind, is_preferred, extension)
#   - emergency_contacts (first_name, last_name, relationship, phone)
#   - insurances (name, plan_type)
#   - pharmacies (name, address, phone)
#   - medications (id, name, dosage, frequency, status, prescribed_date, ...)
#   - patient_story
#   - scenario_complexity
#
# SANDBOX generates at conversation start:
#   - care_team (primary_care_provider) - assigned from generated doctor inventory


ENRICHMENT_PROMPT = """
Generate a complete patient profile and story for a healthcare AI benchmark case.

Seed Attributes:
- Condition: {{condition_name}}
- Severity: {{severity_level}}
- Task: {{task_category}} - {{task_subcategory}}
- Age Group: {{age_group}} (pediatric: 2-17, young_adult: 18-35, middle_aged: 36-64, senior: 65-85)
- Sex: {{sex}}
- Gender: {{gender}}
- Care Preference: {{care_preference}}

Generate a JSON object with the following structure:
{{{{
  "patient_profile": {patient_profile_schema},
  "patient_story": "A detailed 3-5 sentence narrative in third person clinical style...",
  "scenario_complexity": "regular|chronic|complicated|infeasible"
}}}}

Scenario Complexity Guidelines:
- "infeasible": The combination of attributes creates an implausible scenario
- "regular": Standard patient with no significant complications
- "chronic": Patient with conditions requiring continuous care
- "complicated": Multiple comorbidities or overlapping conditions/medications

Requirements:
- Choose a specific age within the age group range
- Use realistic US addresses (real cities/states)
- Use valid US phone number format (10 digits, no dashes)
- Date of birth should match the chosen age
- Names should be diverse and realistic
- Insurance can be "Self Pay" or a realistic insurance provider
- patient_story should include specific symptoms, timeline, and concerns
- patient_story should reflect the care_preference naturally
- patient_story must NOT use specific provider names — refer to providers by role
  (e.g., "their PCP", "their neurologist", "their cardiologist") since actual
  provider names are assigned separately at conversation start
- Generate 2-5 medications based on condition (at least 1 active)

Return ONLY valid JSON, no markdown or explanation.
"""
